### PR TITLE
Document release process

### LINKED ISSUE #47: Document release process
Since we did our first release (https://github.com/ioki-mobility/go-outline/releases/tag/v0.1.0) it make sense to document it. Either just in the Readme or as a separate release.md file.

The document may also contain what we have to do before we can do an release. Eg update version numbers somewhere or making sure that docs are up to date or something.

### PR DESCRIPTION
**Pull request by StefMa**
fixes #47

### CODE REVIEW

**Review by rsjethani — COMMENTED** [review]
IMHO the target audience of this information is a fellow contributor and not the module consumer. Hence it should be in CONTRIBUTING.md file.

**Comment by StefMa** [comment]
I am fine with that 🙃.
But what do you think about a `RELEASE.md`? 🤔

**Comment by rsjethani** [comment]
> I am fine with that 🙃.
> But what do you think about a `RELEASE.md` file? 🤔 

Yes sounds even better 👍

**Review by rsjethani — APPROVED** [review]
Nice, thanks for this

**Pull request merged**
